name: Tests

on: [push, pull_request]

jobs:

  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: '3'
      - name: 'Lint with flake8'
        run: |
          pip install flake8
          flake8 . --count --show-source --statistics

  Pytest:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10]
        os: [ubuntu, macos]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: 'Lint with flake8'
        run: |
          pip install pytest
          python -m pytest

  Build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: ["ubuntu"]
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10]
    env:
      bld_path: /tmp/build
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: 'Deploying miniconda'
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          environment-file: conda.recipes/conda_build_env.yaml
          activate-environment: build
          python-version: ${{ matrix.python-version }}
      - name: 'Set up output folder'
        run: |
          mkdir -p ${bld_path}
      - name: 'Build pip package'
        run: |
          python3 -m build --outdir ${bld_path}
